version: "3"
services:
  client:
    build: .
    depends_on:
      - db
      - api
    env_file:
      - .env
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app:cached
    command: ["npm", "run", "client:start"]
